name: 🧩 Terraform Modules

on:
  push:
    branches: [ modules ]

jobs:
  deploy:
    name: 🏗️ Deploy com Módulos
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      
      - name: 🔧 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0
      
      - name: 🔑 Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      
      - name: ✅ Validate Modules
        run: |
          for module in terraform/modules/*/; do
            echo "📦 Validando $module"
            cd $module
            terraform init -backend=false
            terraform validate
            cd - > /dev/null
          done
      
      - name: ⚙️ Init
        working-directory: terraform/environments/modules
        run: terraform init -upgrade
      
      - name: 📋 Plan
        working-directory: terraform/environments/modules
        run: terraform plan -out=tfplan
      
      - name: 🚀 Apply
        working-directory: terraform/environments/modules
        run: terraform apply -auto-approve tfplan
